parameters:
    revinate_rabbit_mq.connection.class: PhpAmqpLib\Connection\AMQPConnection
    revinate_rabbit_mq.lazy.connection.class: PhpAmqpLib\Connection\AMQPLazyConnection
    revinate_rabbit_mq.queue.class: Revinate\RabbitMqBundle\Queue\Queue
    revinate_rabbit_mq.exchange.class: Revinate\RabbitMqBundle\Exchange\Exchange
    revinate_rabbit_mq.producer.class: Revinate\RabbitMqBundle\Producer\Producer
    revinate_rabbit_mq.consumer.class: Revinate\RabbitMqBundle\Consumer\Consumer
    revinate_rabbit_mq.rpc_consumer.class: Revinate\RabbitMqBundle\Consumer\RPCConsumer
    revinate_rabbit_mq.mock_producer.class: Revinate\RabbitMqBundle\Producer\MockProducer

services:
    revinate.rabbit_mq.base_producer:
        class: Revinate\RabbitMqBundle\Producer\BaseProducer
    revinate.rabbit_mq.default_exchange_producer:
        class: Revinate\RabbitMqBundle\Producer\DefaultExchangeProducer
    revinate.rabbit_mq.services:
        class: Revinate\RabbitMqBundle\Config\Services
    revinate.rabbit_mq.encoder.json:
        class: Revinate\RabbitMqBundle\Encoder\JsonEncoder
    revinate.rabbit_mq.encoder.serialize:
        class: Revinate\RabbitMqBundle\Encoder\SerializeEncoder
    revinate.rabbit_mq.encoder.string:
        class: Revinate\RabbitMqBundle\Encoder\StringEncoder
    revinate.rabbit_mq.decoder.json:
        class: Revinate\RabbitMqBundle\Decoder\JsonDecoder
    revinate.rabbit_mq.decoder.serialize:
        class: Revinate\RabbitMqBundle\Decoder\SerializeDecoder
    revinate.rabbit_mq.decoder.string:
        class: Revinate\RabbitMqBundle\Decoder\StringDecoder