services:
    revinate.amqp_event.producer:
        class: Revinate\RabbitMqBundle\AMQP\AMQPEventProducer
        arguments: [@service_container]
    revinate.amqp_event.consumer:
        class: Revinate\RabbitMqBundle\AMQP\AMQPEventConsumer
        arguments: [@service_container]
